hidden_sizes: [50]
hidden_layers: 2
epochs: 50000
search_space: 'small'
learning_rates: [0.001]
prior_vars: [0.001, 0.01, 0.03, 0.05, 0.07, 0.1, 0.3, 0.5, 0.7, 1., 3., 5., 7., 10., 30., 50.]
batch_size: 1000